apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: file-sharing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: file-service
          image: nazim112/file-service:latest
          ports:
            - containerPort: 8080

          # ---- Datadog APM ----
          env:
            - name: DD_SERVICE
              value: "file-service"
            - name: DD_ENV
              value: "staging"
            - name: DD_VERSION
              value: "1.0.0"
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

            # ---- Postgres env ----
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: "fileuser"
            - name: DB_PASSWORD
              value: "filepassword"
            - name: DB_NAME
              value: "filemanager"

            # ---- Minio env ----
            - name: MINIO_ENDPOINT
              value: "minio:9000"
            - name: MINIO_ACCESS_KEY
              value: "minioadmin"
            - name: MINIO_SECRET_KEY
              value: "minioadmin"
            - name: MINIO_BUCKET
              value: "files"
            - name: MINIO_USE_SSL
              value: "false"

            # ---- NATS env ----
            - name: NATS_URL
              value: "nats://nats:4222"

            # ---- Keycloak env ----
            - name: KEYCLOAK_URL
              value: "http://keycloak-http:80/realms/bondbridg"

            # ---- Other env ----
            - name: SERVER_PORT
              value: "8080"

          resources:
            requests:
              memory: "256Mi"
            limits:
              memory: "512Mi"